name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@latest
      - run: pnpm i
      - run: pnpm build
      - uses: codecov/codecov-action@v2
        with:
          directory: ./packages/severed/coverage

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g pnpm@latest
      - run: pnpm i
      - run: pnpm build
